### ISSUE TITLE
IDE cannot access generated sources from lich savedstate compiler

### ISSUE THREAD

**Issue by ganadist** [line/lich#111]
Related issue : https://github.com/google/ksp/issues/746

When using ksp and savedstate compiler, IDE(such as Android Studio) cannot resolve symbols from generated sources as default.

![image](https://user-images.githubusercontent.com/221114/145130590-b9e938de-3639-4341-a469-62f61c01705a.png)

In this case, many IDE feature will be malfunction such as `Code Formatting`

In other libraries cases such as `Room` which are providing annotation processors, library provides `Builder` API which are wrapping generated sources and allow to access.

ex : https://developer.android.com/training/data-storage/room#usage

Similar to `Room`, is it possible to avoid referencing the generated code directly?

**Comment by yamasa** [comment]
As you may have already noticed, this is a problem that should be solved on the KSP Gradle Plugin (or Android Gradle Plugin?) side.

> is it possible to avoid referencing the generated code directly?

There is no plan to introduce such a workaround as it would break the existing code.

You can *manually* add the generated codes as "Generated Sources Root" as follows:
<img width="708" alt="screenshot" src="https://user-images.githubusercontent.com/143949/145957024-e66db235-4961-4ca1-9de4-8b9b9d7af930.png">
