### ISSUE TITLE
[Improvement] resumeWith and resumeWithException needs to be cooperative

### ISSUE THREAD

**Issue by radityagumay** [line/lich#42]
### Background
It's a best practice to be cooperative to check the state of cancellable on [suspendCancellableCoroutine](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/CancellableContinuation.kt#L52).

Especially on this [resumeWith](https://github.com/line/lich/blob/master/okhttp/src/main/java/com/linecorp/lich/okhttp/OkHttpExtensions.kt#L66) and [resumeWithException](https://github.com/line/lich/blob/master/okhttp/src/main/java/com/linecorp/lich/okhttp/OkHttpExtensions.kt#L70) which manifested on [OkHttpExtensions.kt](https://github.com/line/lich/blob/master/okhttp/src/main/java/com/linecorp/lich/okhttp/OkHttpExtensions.kt#L59).

The rationale of having cooperative implementation basically to make sure the invocation does not throw an exception such as [CompletionHandlerException](https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt#L239) on the call-site.

### Proposal of changes
from
```kotlin
suspend fun <T> OkHttpClient.call(request: Request, responseHandler: (Response) -> T): T =
    suspendCancellableCoroutine { cont ->
        val call = newCall(request)
        cont.invokeOnCancellation { call.cancel() }
        call.enqueue(object : Callback {
            override fun onResponse(call: Call, response: Response) {
                val result = runCatching { response.use(responseHandler) }
                cont.resumeWith(result)
            }

            override fun onFailure(call: Call, e: IOException) {
                cont.resumeWithException(e)
            }
        })
    }
```

to
```kotlin
suspend fun <T> OkHttpClient.call(request: Request, responseHandler: (Response) -> T): T =
    suspendCancellableCoroutine { cont ->
        val call = newCall(request)
        cont.invokeOnCancellation { call.cancel() }
        call.enqueue(object : Callback {
            override fun onResponse(call: Call, response: Response) {
                if (cont.isActive) {
                    val result = runCatching { response.use(responseHandler) }
                    cont.resumeWith(result)
                }
             }

            override fun onFailure(call: Call, e: IOException) {
               if (cont.isActive) {
                   cont.resumeWithException(e)
               }
            }
        })
    }
```

**Comment by yamasa** [comment]
We don't need to check the cancellation status before calling resumeWith / resumeWithException.
For details, please refer the comment below.
https://github.com/Kotlin/kotlinx.coroutines/issues/830#issuecomment-447819778
